version: "3"

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  provider:
    image: japp
    restart: on-failure
    depends_on:
      - rabbitmq

  consumer:
    image: rpc-client
    restart: on-failure
    depends_on:
      - rabbitmq



